version '4.0'

services:
   
   mongo1:
      image: mongo:latest
      restart: always
      container_name: mongo1container
      environment:
        MONGO_INITDB_ROOT_USERNAME: hari
        MONGO_INITDB_ROOT_PASSWORD: hari@123
      volumes:
       - ./mongod1.conf:/etc/mongod1.conf
      ports:
       - 27018:27017
      command: ["mongod","--config","/etc/mongod1.conf"]

   mongo-express:
     image: mongo-express
     restart: always
     ports:
      - 8081:8081
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: hari
       ME_CONFIG_MONGODB_ADMINPASSWORD: hari@123
       ME_CONFIG_MONGODB_URL: mongodb://hari:hari%40123@mongo1container:27017/
       ME_CONFIG_BASICAUTH: false


       
